---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-1-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-1
spec:
  type: ClusterIP
  ports:
    - port: 5678
      protocol: TCP
      targetPort: 5678
      name: port-5678
    - port: 4000
      protocol: UDP
      targetPort: 4000
      name: port-4000
    - port: 5000
      protocol: TCP
      targetPort: 5000
      name: port-5000        
  selector:
    app: ssv-node-1
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: ssv-node-1
  name: ssv-node-1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-1
  template:
    metadata:
      labels:
        app: ssv-node-1
    spec:
      containers:
      - name: ssv-node-1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-node"]
        ports:
        - containerPort: 4000
          name: port-4000
          protocol: UDP
        - containerPort: 5000
          name: port-5000
        - containerPort: 5678
          name: port-5678
        env:
        - name: NODE_ID
          value: "1"
        - name: SSV_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_node_1
        - name: VALIDATOR_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: validator_public_key
        - name: BEACON_NODE_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beacon_node_addr
        - name: PUBKEY_NODE_2
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_2
        - name: PUBKEY_NODE_3
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_3
        - name: PUBKEY_NODE_4
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_4
        - name: NETWORK
          value: "pyrmont" 
        - name: CONSENSUS_TYPE
          value: "validation"
      - name: ssv-node-2
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-node"]
        ports:
        - containerPort: 5678
          name: port-5678
        env:
        - name: NODE_ID
          value: "2"
        - name: SSV_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_node_2
        - name: VALIDATOR_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: validator_public_key
        - name: BEACON_NODE_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beacon_node_addr
        - name: PUBKEY_NODE_1
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_1
        - name: PUBKEY_NODE_3
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_3
        - name: PUBKEY_NODE_4
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_4
        - name: NETWORK
          value: "pyrmont" 
        - name: CONSENSUS_TYPE
          value: "validation"
      - name: ssv-node-3
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-node"]
        ports:
        - containerPort: 5678
          name: port-5678
        env:
        - name: NODE_ID
          value: "3"
        - name: SSV_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: ssv_node_3
        - name: VALIDATOR_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: validator_public_key
        - name: BEACON_NODE_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: beacon_node_addr
        - name: PUBKEY_NODE_1
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_1
        - name: PUBKEY_NODE_2
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_2
        - name: PUBKEY_NODE_4
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: pubkey_node_4
        - name: NETWORK
          value: "pyrmont" 
        - name: CONSENSUS_TYPE
          value: "validation"
      - name: ssv-node-4
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        command: ["make", "start-node"]
        ports:
          - containerPort: 5678
            name: port-5678
        env:
          - name: NODE_ID
            value: "4"
          - name: SSV_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: ssv_node_4
          - name: VALIDATOR_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: validator_public_key
          - name: BEACON_NODE_ADDR
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: beacon_node_addr
          - name: PUBKEY_NODE_1
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: pubkey_node_1
          - name: PUBKEY_NODE_2
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: pubkey_node_2
          - name: PUBKEY_NODE_3
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: pubkey_node_3
          - name: NETWORK
            value: "pyrmont"
          - name: CONSENSUS_TYPE
            value: "validation"
