---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-8-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-8
spec:
  type: ClusterIP
  ports:
    - port: 12010
      protocol: UDP
      targetPort: 12010
      name: port-12010
    - port: 13010
      protocol: TCP
      targetPort: 13010
      name: port-13010
    - port: 15010
      protocol: TCP
      targetPort: 15010
      name: port-15010
  selector:
    app: ssv-node-8
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: ssv-node-8
  name: ssv-node-8
  namespace: REPLACE_NAMESPACE
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-8
  template:
    metadata:
      labels:
        app: ssv-node-8
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-8
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12010
          name: port-12010
          protocol: UDP
          hostPort: 12010            
        - containerPort: 13010
          name: port-13010
          hostPort: 13010
        - containerPort: 15010
          name: port-15010
          hostPort: 15010
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: ETH_1_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth1_addr
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node_v2
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key_v2
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version_v2
              optional: true
        - name: NETWORK_ID
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: network_id_v2
              optional: true
        - name: FORKV2_EPOCH
          value: '1'
        - name: LOG_LEVEL
          value: "debug"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: GENESIS_EPOCH
          value: "1"
        - name: LOGGER_LEVEL
          value: "debug"
        - name: DB_PATH
          value: "./data/db"
        - name: DB_REPORTING
          value: "true"
        - name: METRICS_API_PORT
          value: "15010"
        - name: ENABLE_PROFILE
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-8
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-8
#      - name: ubuntu
#        image: REPLACE_HEALTH_IMAGE
#        imagePullPolicy: Always
#        args: [bash, -c, sleep infinity]
#        volumeMounts:
#        - name: ssv-nodes-health-check-cm
#          mountPath: /root/http-status.sh
#          subPath: http-status.sh
#        livenessProbe:
#          exec:
#            command:
#            - /bin/bash
#            - /root/http-status.sh
#          initialDelaySeconds: 120
#          periodSeconds: 60
      volumes:
      - name: ssv-node-8
        persistentVolumeClaim:
          claimName: ssv-node-8
      - name: ssv-cm-validator-options-8
        configMap:
          name: ssv-cm-validator-options-8
#      - name: ssv-nodes-health-check-cm
#        configMap:
#          name: ssv-nodes-health-check-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
