---
apiVersion: v1
kind: Service
metadata:
  name: node-c-3-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: node-c-3
spec:
  type: ClusterIP
  ports:
    - port: 12011
      protocol: UDP
      targetPort: 12011
      name: port-12011
    - port: 13011
      protocol: TCP
      targetPort: 13011
      name: port-13011
    - port: 15011
      protocol: TCP
      targetPort: 15011
      name: port-15011
  selector:
    app: node-c-3
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: node-c-3
  name: node-c-3
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-c-3
  template:
    metadata:
      labels:
        app: node-c-3
    spec:
      containers:
      - name: node-c-3
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu:  {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.mem }}
        command: ["make", "start-node"]
        ports:
        - containerPort: 12011
          name: port-12011
          protocol: UDP
          hostPort: 12011            
        - containerPort: 13011
          name: port-13011
          hostPort: 13011
        - containerPort: 15011
          name: port-15011
          hostPort: 15011
        env:
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: LOGGER_LEVEL
          value: "debug"
        - name: DB_PATH
          value: "./data/db-v3"
        - name: DB_REPORTING
          value: "false"
        - name: METRICS_API_PORT
          value: "15011"
        - name: ENABLE_PROFILE
          value: "true"
        - name: DISCOVERY_TRACE
          value: 'false'
        - name: PUBSUB_TRACE
          value: 'false'
        - name: NETWORK_ID
          value: "shifu-v2-stage"
        - name: GENESIS_EPOCH
          value: "152834"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-11
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-c-3
      volumes:
      - name: ssv-node-11
        persistentVolumeClaim:
          claimName: ssv-node-11
      - name: ssv-cm-validator-options-ssv-node-cluster-c-3
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-c-3
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
