---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-11-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-11
spec:
  type: ClusterIP
  ports:
    - port: 12011
      protocol: UDP
      targetPort: 12011
      name: port-12011
    - port: 13011
      protocol: TCP
      targetPort: 13011
      name: port-13011
    - port: 15011
      protocol: TCP
      targetPort: 15011
      name: port-15011
  selector:
    app: ssv-node-11
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: ssv-node-11
  name: ssv-node-11
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-11
  template:
    metadata:
      labels:
        app: ssv-node-11
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-11
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12011
          name: port-12011
          protocol: UDP
          hostPort: 12011            
        - containerPort: 13011
          name: port-13011
          hostPort: 13011
        - containerPort: 15011
          name: port-15011
          hostPort: 15011
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: ETH_1_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth1_addr
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: ENR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: enr_key
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: LOG_LEVEL
          value: "debug"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: GENESIS_EPOCH
          value: "1"
        - name: LOGGER_LEVEL
          value: "debug"
        - name: DB_PATH
          value: "./data/db"
        - name: DB_REPORTING
          value: "true"
        - name: METRICS_API_PORT
          value: "15011"
        - name: ENABLE_PROFILE
          value: "true"
        - name: BOOTNODES
          value: "enr:-LK4QDAmZK-611qRU5q-cxW6BqLwIlWoYH-BoRlX2N7D11rXBlM7OJ11tWRRtryqvCW04geHC_ab11QmWT11QULnT0Tc5S1cBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhArqAsGJc2VjcDI1NmsxoQO11KQz5L1UEXzEr-CXFFq1th0eG6gopbdul2OQVMuxfMoN0Y3CCE4iDdWRwgg-g"
        - name: DISCOVERY_TRACE
          value: 'true'
        - name: PUBSUB_TRACE
          value: 'true'
        volumeMounts:
        - mountPath: /data
          name: ssv-node-11
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-11
#      - name: ubuntu
#        image: REPLACE_HEALTH_IMAGE
#        imagePullPolicy: Always
#        args: [bash, -c, sleep infinity]
#        volumeMounts:
#        - name: ssv-nodes-health-check-cm
#          mountPath: /root/http-status.sh
#          subPath: http-status.sh
#        livenessProbe:
#          exec:
#            command:
#            - /bin/bash
#            - /root/http-status.sh
#          initialDelaySeconds: 120
#          periodSeconds: 60
      volumes:
      - name: ssv-node-11
        persistentVolumeClaim:
          claimName: ssv-node-11
      - name: ssv-cm-validator-options-11
        configMap:
          name: ssv-cm-validator-options-11
#      - name: ssv-nodes-health-check-cm
#        configMap:
#          name: ssv-nodes-health-check-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true   
