---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-v3-2-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-v3-2
spec:
  type: ClusterIP
  ports:
    - port: 12302
      protocol: UDP
      targetPort: 12302
      name: port-12302
    - port: 13302
      protocol: TCP
      targetPort: 13302
      name: port-13302
    - port: 15302
      protocol: TCP
      targetPort: 15302
      name: port-15302
    - port: 16302
      protocol: TCP
      targetPort: 16302
      name: port-16302
  selector:
    app: ssv-node-v3-2
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-v3-2
  name: ssv-node-v3-2
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-v3-2
  template:
    metadata:
      labels:
        app: ssv-node-v3-2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-v3-2
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12302
          name: port-12302
          protocol: UDP
          hostPort: 12302
        - containerPort: 13302
          name: port-13302
          hostPort: 13302
        - containerPort: 15302
          name: port-15302
          hostPort: 15302
        - containerPort: 16302
          name: port-16302
          hostPort: 16302
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db-jato-v2"
        - name: NETWORK
          value: "jato-v2-stage"
        - name: METRICS_API_PORT
          value: "15302"
        - name: SSV_API_PORT
          value: "16302"
        - name: ENABLE_PROFILE
          value: "true"
        - name: BUILDER_PROPOSALS
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-2
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-v3-2
      volumes:
      - name: ssv-node-v3-2
        persistentVolumeClaim:
          claimName: ssv-node-v3-2
      - name: ssv-cm-validator-options-v3-2
        configMap:
          name: ssv-cm-validator-options-v3-2
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
