---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-v3-3-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-v3-3
spec:
  type: ClusterIP
  ports:
    - port: 12303
      protocol: UDP
      targetPort: 12303
      name: port-12303
    - port: 13303
      protocol: TCP
      targetPort: 13303
      name: port-13303
    - port: 15303
      protocol: TCP
      targetPort: 15303
      name: port-15303
    - port: 16303
      protocol: TCP
      targetPort: 16303
      name: port-16303
    - port: 16303
      protocol: TCP
      targetPort: 16303
      name: port-16303
  selector:
    app: ssv-node-v3-3
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-v3-3
  name: ssv-node-v3-3
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-v3-3
  template:
    metadata:
      labels:
        app: ssv-node-v3-3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-v3-3
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12303
          name: port-12303
          protocol: UDP
          hostPort: 12303
        - containerPort: 13303
          name: port-13303
          hostPort: 13303
        - containerPort: 15303
          name: port-15303
          hostPort: 15303
        - containerPort: 16303
          name: port-16303
          hostPort: 16303
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db-jato-v2"
        - name: NETWORK
          value: "jato-v2-stage"
        - name: METRICS_API_PORT
          value: "15303"
        - name: SSV_API_PORT
          value: "16303"
        - name: ENABLE_PROFILE
          value: "true"
        - name: WS_API_PORT
          value: "16303"
        - name: FULLNODE
          value: "true"
        - name: BUILDER_PROPOSALS
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-3
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-v3-3
      volumes:
      - name: ssv-node-v3-3
        persistentVolumeClaim:
          claimName: ssv-node-v3-3
      - name: ssv-cm-validator-options-v3-3
        configMap:
          name: ssv-cm-validator-options-v3-3
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
