---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-v3-4-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-v3-4
spec:
  type: ClusterIP
  ports:
    - port: 12304
      protocol: UDP
      targetPort: 12304
      name: port-12304
    - port: 13304
      protocol: TCP
      targetPort: 13304
      name: port-13304
    - port: 15304
      protocol: TCP
      targetPort: 15304
      name: port-15304
    - port: 16304
      protocol: TCP
      targetPort: 16304
      name: port-16304
  selector:
    app: ssv-node-v3-4
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-v3-4
  name: ssv-node-v3-4
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-v3-4
  template:
    metadata:
      labels:
        app: ssv-node-v3-4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-v3-4
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12304
          name: port-12304
          protocol: UDP
          hostPort: 12304
        - containerPort: 13304
          name: port-13304
          hostPort: 13304
        - containerPort: 15304
          name: port-15304
          hostPort: 15304
        - containerPort: 16304
          name: port-16304
          hostPort: 16304
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db-jato-v2"
        - name: NETWORK
          value: "jato-v2-stage"
        - name: METRICS_API_PORT
          value: "15304"
        - name: SSV_API_PORT
          value: "16304"
        - name: ENABLE_PROFILE
          value: "true"
        - name: BUILDER_PROPOSALS
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-4
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-v3-4
      volumes:
      - name: ssv-node-v3-4
        persistentVolumeClaim:
          claimName: ssv-node-v3-4
      - name: ssv-cm-validator-options-v3-4
        configMap:
          name: ssv-cm-validator-options-v3-4
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
