---
apiVersion: v1
kind: Service
metadata:
  name: node-d-4-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: node-d-4
spec:
  type: ClusterIP
  ports:
    - port: 12304
      protocol: UDP
      targetPort: 12304
      name: port-12304
    - port: 13304
      protocol: TCP
      targetPort: 13304
      name: port-13304
    - port: 15304
      protocol: TCP
      targetPort: 15304
      name: port-15304
  selector:
    app: node-d-4
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: node-d-4
  name: node-d-4
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-d-4
  template:
    metadata:
      labels:
        app: node-d-4
    spec:
      containers:
      - name: node-d-4
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu:  {{ .Values.resources.limits_node_4.cpu }}
            memory: {{ .Values.resources.limits_node_4.mem }}            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12304
          name: port-12304
          protocol: UDP
          hostPort: 12304            
        - containerPort: 13304
          name: port-13304
          hostPort: 13304
        - containerPort: 15304
          name: port-15304
          hostPort: 15304
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: P2P_LOG
          value: "false"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db"
        - name: METRICS_API_PORT
          value: "15304"
        - name: ENABLE_PROFILE
          value: "true"
        - name: NETWORK_ID
          value: "shifu-v2-stage"
        - name: GENESIS_EPOCH
          value: "152834"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-4
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-d-4
      volumes:
      - name: ssv-node-v3-4
        persistentVolumeClaim:
          claimName: ssv-node-v3-4
      - name: ssv-cm-validator-options-ssv-node-cluster-d-4
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-d-4
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
