global:
  LogLevel: info

db:
  Path: ./data/db/exporter
  Type: badger-db

BeaconNodeAddr: prater-4000-ext.stage.bloxinfra.com:80
ETH1Addr: ws://eth1-ws-ext.stage.bloxinfra.com/ws

p2p:
  HostAddress:
