global:
  LogLevel: info

db:
  Path: ./data/db

eth2:
  BeaconNodeAddr: example.url
  Network: prater

eth1:
  # ETH1 node WebSocket address
  ETH1Addr: example.url

p2p:
  # replace with your ip
  HostAddress: example.ip
  TcpPort:
  UdpPort:
  # mdns for local network setup
  DiscoveryType: mdns

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:

bootnode:
  ExternalIP:
  PrivateKey:
