global:
  LogLevel: debug

db:
  Path: ./data/db

eth2:
  BeaconNodeAddr: example.url
  Network: prater

eth1:
  # ETH1 node WebSocket address
  ETH1Addr: example.url

p2p:
  # replace with your ip
#  HostAddress: example.ip
#  TcpPort:
#  UdpPort:
# mdns for local network setup
#  Discovery: mdns

ssv:
  GenesisEpoch:
  ValidatorOptions:
    SignatureCollectionTimeout: 5s
    FullNode: true
    Exporter: true

GenerateOperatorPrivateKey: true

bootnode:
  ExternalIP:
  PrivateKey:

LocalEventsPath: # path to local events. used for running the node with custom local events
WebSocketAPIPort: 16000
