global:
  LogLevel: info

db:
  Path: ./data/db/exporter
  Type: badger-db

eth2:
  BeaconNodeAddr: prater-4000-ext.stage.bloxinfra.com:80

eth1:
  ETH1Addr: ws://eth1-ws-ext.stage.bloxinfra.com/ws

p2p:
  HostAddress:
