---
apiVersion: v1
kind: Service
metadata:
  name: node-3-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: node-3
spec:
  type: ClusterIP
  ports:
    - port: 12003
      protocol: UDP
      targetPort: 12003
      name: port-12003
    - port: 13003
      protocol: TCP
      targetPort: 13003
      name: port-13003
    - port: 15003
      protocol: TCP
      targetPort: 15003
      name: port-15003
  selector:
    app: node-3
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: node-3
  name: node-3
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: node-3
  template:
    metadata:
      labels:
        app: node-3
    spec:
      containers:
      - name: node-3
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu:  {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.mem }}            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12003
          name: port-12003
          protocol: UDP
          hostPort: 12003            
        - containerPort: 13003
          name: port-13003
          hostPort: 13003
        - containerPort: 15003
          name: port-15003
          hostPort: 15003
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: TCP_PORT
          value: "13003"
        - name: UDP_PORT
          value: "12003"
        - name: LOGGER_LEVEL
          value: "debug"
        - name: DB_PATH
          value: "./data/db-v3"
        - name: DB_REPORTING
          value: "false"
        - name: METRICS_API_PORT
          value: "15003"
        - name: ENABLE_PROFILE
          value: "true"
        - name: DISCOVERY_TRACE
          value: 'false'
        - name: PUBSUB_TRACE
          value: 'false'
        - name: NETWORK_ID
          value: "shifu-v2-stage"
        - name: GENESIS_EPOCH
          value: "152834"
        - name: P2P_LOG
          value: "false"
        - name: CLEAN_REGISTRY_DATA
          value: "false"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v2-3
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-a-3
      volumes:
      - name: ssv-node-v2-3
        persistentVolumeClaim:
          claimName: ssv-node-v2-3
      - name: ssv-cm-validator-options-ssv-node-cluster-a-3
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-a-3
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
