---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-mainnet-2-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-mainnet-2
spec:
  type: ClusterIP
  ports:
    - port: 12018
      protocol: UDP
      targetPort: 12018
      name: port-12018
    - port: 13018
      protocol: TCP
      targetPort: 13018
      name: port-13018
    - port: 15018
      protocol: TCP
      targetPort: 15018
      name: port-15018
    - port: 16018
      protocol: TCP
      targetPort: 16018
      name: port-16018
  selector:
    app: ssv-node-mainnet-2
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-mainnet-2
  name: ssv-node-mainnet-2
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-mainnet-2
  template:
    metadata:
      labels:
        app: ssv-node-mainnet-2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-node-mainnet-2
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12018
          name: port-12018
          hostPort: 12018
          protocol: UDP
        - containerPort: 13018
          name: port-13018
          hostPort: 13018
        - containerPort: 15018
          name: port-15018
          hostPort: 15018
        - containerPort: 16018
          name: port-16018
          hostPort: 16018
        env:
          - name: SHARE_CONFIG
            value: "./data1/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "mainnet"
          - name: CONSENSUS_TYPE
            value: "validation"
          - name: HOST_DNS
            value: ""
          - name: HOST_ADDRESS
            value: ""
          - name: DB_PATH
            value: "./data/db-mainnet"
          - name: METRICS_API_PORT
            value: "15018"
          - name: SSV_API_PORT
            value: "16018"
          - name: ENABLE_PROFILE
            value: "true"
          - name: BUILDER_PROPOSALS
            value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-mainnet-2
        - mountPath: /data1/share.yaml
          subPath: share.yaml
          name: ssv-node-mainnet-2-cm
      volumes:
      - name: ssv-node-mainnet-2
        persistentVolumeClaim:
          claimName: ssv-node-mainnet-2
      - name: ssv-node-mainnet-2-cm
        configMap:
          name: ssv-node-mainnet-2-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
