# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 
  ssv_exporter_1: 1
  ssv_exporter_2: 1

namespace: blockchain

domain: stage.ssv.network

image:
  repository: 121827225315.dkr.ecr.us-west-2.amazonaws.com/ssv-node
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

resources:
  limits_exporter_1:
    cpu: 1000m
    mem: 1024Mi
  limits_exporter_2:
    cpu: 1000m
    mem: 1024Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/role
              operator: In
              values:
                - ssv-main
tolerations:
  - effect: NoSchedule
    key: kubernetes.io/role
    operator: Exists
