---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-prater-2-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-prater-2
spec:
  type: ClusterIP
  ports:
    - port: 12012
      protocol: UDP
      targetPort: 12012
      name: port-12012
    - port: 13012
      protocol: TCP
      targetPort: 13012
      name: port-13012
    - port: 15012
      protocol: TCP
      targetPort: 15012
      name: port-15012
    - port: 16012
      protocol: TCP
      targetPort: 16012
      name: port-16012
  selector:
    app: ssv-node-prater-2
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-prater-2
  name: ssv-node-prater-2
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-prater-2
  template:
    metadata:
      labels:
        app: ssv-node-prater-2
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-node-prater-2
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12012
          name: port-12012
          hostPort: 12012
          protocol: UDP
        - containerPort: 13012
          name: port-13012
          hostPort: 13012
        - containerPort: 15012
          name: port-15012
          hostPort: 15012
        - containerPort: 16012
          name: port-16012
          hostPort: 16012
        env:
          - name: SHARE_CONFIG
            value: "./data1/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "jato-v2"
          - name: CONSENSUS_TYPE
            value: "validation"
          - name: HOST_DNS
            value: ""
          - name: HOST_ADDRESS
            value: ""
          - name: DB_PATH
            value: "./data/db-jato-v2"
          - name: METRICS_API_PORT
            value: "15012"
          - name: SSV_API_PORT
            value: "16012"
          - name: ENABLE_PROFILE
            value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-prater-2
        - mountPath: /data1/share.yaml
          subPath: share.yaml
          name: ssv-node-prater-2-cm
      volumes:
      - name: ssv-node-prater-2
        persistentVolumeClaim:
          claimName: ssv-node-prater-2
      - name: ssv-node-prater-2-cm
        configMap:
          name: ssv-node-prater-2-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
