---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-prater-4-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-prater-4
spec:
  type: ClusterIP
  ports:
    - port: 12014
      protocol: UDP
      targetPort: 12014
      name: port-12014
    - port: 13014
      protocol: TCP
      targetPort: 13014
      name: port-13014
    - port: 15014
      protocol: TCP
      targetPort: 15014
      name: port-15014
    - port: 16014
      protocol: TCP
      targetPort: 16014
      name: port-16014
  selector:
    app: ssv-node-prater-4
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-prater-4
  name: ssv-node-prater-4
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-prater-4
  template:
    metadata:
      labels:
        app: ssv-node-prater-4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-node-prater-4
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12014
          name: port-12014
          hostPort: 12014
          protocol: UDP
        - containerPort: 13014
          name: port-13014
          hostPort: 13014
        - containerPort: 15014
          name: port-15014
          hostPort: 15014
        - containerPort: 16014
          name: port-16014
          hostPort: 16014
        env:
          - name: SHARE_CONFIG
            value: "./data1/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "jato-v2"
          - name: CONSENSUS_TYPE
            value: "validation"
          - name: HOST_DNS
            value: ""
          - name: HOST_ADDRESS
            value: ""
          - name: DB_PATH
            value: "./data/db-jato-v2"
          - name: METRICS_API_PORT
            value: "15014"
          - name: SSV_API_PORT
            value: "16014"
          - name: ENABLE_PROFILE
            value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-prater-4
        - mountPath: /data1/share.yaml
          subPath: share.yaml
          name: ssv-node-prater-4-cm
      volumes:
      - name: ssv-node-prater-4
        persistentVolumeClaim:
          claimName: ssv-node-prater-4
      - name: ssv-node-prater-4-cm
        configMap:
          name: ssv-node-prater-4-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
