name: Degradation test

on:
  push:
    branches:
      - "**"

jobs:
  performance-degradation-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"

      - name: Tidy up dependencies
        run: go mod tidy

      - name: Install yq
        run: sudo snap install yq

      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Build degradation tester tool
        run: |
          cd ./scripts/degradation-tester
          go install .

      - name: Run degradation-test
        run: |
          make degradation-test
        env:
          GO111MODULE: on
