name: Run dutytracer collector benchmark
run-name: ${{ github.actor }} started workflow üöÄ

on:
  workflow_dispatch:
  push:
    branches:
      - feat/exporter-v2

jobs:
  Test-with-LFS:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          lfs: true # Ensure Git LFS files are fetched

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.24.x"

      - name: Run benchmark
        id: bench
        run: |
          go test -benchmem -run=^$ -bench ^BenchmarkTracer$ github.com/ssvlabs/ssv/operator/dutytracer -v

      - name: Run eviction test
        id: eviction
        run: |
          go test -tags lfs -timeout 5s -run ^TestEviction$ github.com/ssvlabs/ssv/operator/dutytracer -v

      - run: echo "üçè This job's status is ${{ job.status }}."
