name: Run dutytracer collector benchmark
run-name: ${{ github.actor }} started workflow ğŸš€

on:
  workflow_dispatch:
  push:
    branches:
      - stage

jobs:
  Test-with-LFS:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          lfs: true # Ensure Git LFS files are fetched

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Run benchmark
        id: bench
        run: |
          go test -benchmem -run=^$ -bench ^BenchmarkTracer$ github.com/ssvlabs/ssv/operator/dutytracer -v

      - name: Run eviction test
        id: eviction
        run: |
          go test -tags lfs -timeout 5s -run ^TestEviction$ github.com/ssvlabs/ssv/operator/dutytracer -v

      - run: echo "ğŸ This job's status is ${{ job.status }}."
