name: Lint

on: push

jobs:
  lint:
ï¿¼   runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/checkout@v2

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make
       
      - name: Run lint-prepare 
        run: make lint-prepare

      - name: Run make lint
        run: make lint
