name: Test coverage

on:
#  push:
#    branches:
#      - "stage"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Run make test
        run: make full-test COVERAGE=true

      - name: Create coverage badge
        if: ${{ success() }}
        run: |
          [ -f coverage.out ] && echo "processing coverage output file" || echo "could not find coverage output file"
          COV_TOTAL=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Code coverage: $COV_TOTAL"
          if (( $(echo "$COV_TOTAL <= 50" | bc -l) )) ; then
            COV_COLOR=red
          elif (( $(echo "$COV_TOTAL > 80" | bc -l) )); then
            COV_COLOR=green
          else
            COV_COLOR=orange
          fi
          curl "https://img.shields.io/badge/coverage-$COV_TOTAL%25-$COV_COLOR" > ./docs/resources/cov-badge.svg

      - name: Publish coverage badge
        if: ${{ success() }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/resources/cov-badge.svg
          git commit -m "update code coverage badge" && git push || echo "No changes"
